name: Simple Usage

on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  convert_via_pandoc:  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # this gives the workflow access to your repository files
      - name: Run Pandoc on main tex file
        run: "pandoc -F pandoc-crossref --citeproc -t html -s -o article.html main.tex" # gets appended to pandoc command      
      - name: Print Out Files 
        run: "ls ./* > test.html"                

  make_pdf:  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    container:
      image: docker://leplusorg/latex:sha-373ec13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # this gives the workflow access to your repository files
      # - name: Try and make a pdf from tex file
      #   run: "pdflatex main.tex" 
      #   continue-on-error: true
      # - name: Print Out Files 
      #   run: "ls ./* > test.html"                        
      
  
  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: make_pdf
  #   steps:
  #     - name: Setup Pages
  #       uses: actions/configure-pages@v3
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:          
  #         path: '.' # Upload entire repository
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4

