name: Simple Usage

on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  convert_via_pandoc:  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.17
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # this gives the workflow access to your repository files
      - name: Run Pandoc on main tex file
        run: "pandoc -F pandoc-crossref --citeproc -t html -s -o test.html main.tex" # gets appended to pandoc command
      - name: Try and make a pdf from tex file
        run: "pandoc -s -o article.pdf main.tex" 
        continue-on-error: true
      - name: Print Out Files 
        run: "ls ./* > test.html"          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:          
          path: '.' # Upload entire repository
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
